[data.colors]
name = "frappe"
foreground = "#c6d0f5"
background = "#303446"

black = "#51576d"
bright_black = "#626880"
red = "#e78284"
bright_red = "#e78284"
green = "#a6d189"
bright_green = "#a6d189"
yellow = "#e5c890"
bright_yellow = "#e5c890"
blue = "#8caaee"
bright_blue = "#8caaee"
magenta = "#f4b8e4"
bright_magenta = "#f4b8e4"
cyan = "#81c8be"
bright_cyan = "#81c8be"
white = "#b5bfe2"
bright_white = "#a5adce"

extended_16 = "#f4b8e4"
extended_17 = "#e78284"

base00 = "#303446"
base01 = "#292c3c"
base02 = "#414559"
base03 = "#51576d"
base04 = "#626880"
base05 = "#c6d0f5"
base06 = "#f2d5cf"
base07 = "#babbf1"
base08 = "#e78284"
base09 = "#ef9f76"
base0A = "#e5c890"
base0B = "#a6d189"
base0C = "#81c8be"
base0D = "#8caaee"
base0E = "#ca9ee6"
base0F = "#eebebe"
