[data.colors]
name = "macchiato"
foreground = "#cad3f5"
background = "#24273a"

black = "#494d64"
bright_black = "#5b6078"
red = "#ed8796"
bright_red = "#ed8796"
green = "#a6da95"
bright_green = "#a6da95"
yellow = "#eed49f"
bright_yellow = "#eed49f"
blue = "#8aadf4"
bright_blue = "#8aadf4"
magenta = "#f5bde6"
bright_magenta = "#f5bde6"
cyan = "#8bd5ca"
bright_cyan = "#8bd5ca"
white = "#b8c0e0"
bright_white = "#a5adcb"

extended_16 = "#f5bde6"
extended_17 = "#ed8796"

base00 = "#24273a"
base01 = "#1e2030"
base02 = "#363a4f"
base03 = "#494d64"
base04 = "#5b6078"
base05 = "#cad3f5"
base06 = "#f4dbd6"
base07 = "#b7bdf8"
base08 = "#ed8796"
base09 = "#f5a97f"
base0A = "#eed49f"
base0B = "#a6da95"
base0C = "#8bd5ca"
base0D = "#8aadf4"
base0E = "#c6a0f6"
base0F = "#f0c6c6"
