[data.colors]
name = "mocha"
foreground = "#cdd6f4"
background = "#1e1e2e"
black = "#45475a"
bright_black = "#585b70"
red = "#f38ba8"
bright_red = "#f38ba8"
green = "#a6e3a1"
bright_green = "#a6e3a1"
yellow = "#f9e2af"
bright_yellow = "#f9e2af"
blue = "#89b4fa"
bright_blue = "#89b4fa"
magenta = "#f5c2e7"
bright_magenta = "#f5c2e7"
cyan = "#94e2d5"
bright_cyan = "#94e2d5"
white = "#bac2de"
bright_white = "#a6adc8"
extended_16 = "#f5c2e7"
extended_17 = "#f38ba8"

base00 = "#1e1e2e"
base01 = "#181825"
base02 = "#313244"
base03 = "#45475a"
base04 = "#585b70"
base05 = "#cdd6f4"
base06 = "#f5e0dc"
base07 = "#b4befe"
base08 = "#f38ba8"
base09 = "#fab387"
base0A = "#f9e2af"
base0B = "#a6e3a1"
base0C = "#94e2d5"
base0D = "#89b4fa"
base0E = "#cba6f7"
base0F = "#f2cdcd"
