[data.colors]
name = "dracula"
foreground = "#f8f8f2"
background = "#282a36"

black = "#21222c"
bright_black = "#6272a4"
red = "#ff5555"
bright_red = "#ff6e6e"
green = "#50fa7b"
bright_green = "#69ff94"
yellow = "#f1fa8c"
bright_yellow = "#ffffa5"
blue = "#bd93f9"
bright_blue = "#d6acff"
magenta = "#ff79c6"
bright_magenta = "#ff92df"
cyan = "#8be9fd"
bright_cyan = "#a4ffff"
white = "#f8f8f2"
bright_white = "#ffffff"

extended_16 = "#ffb86c"
extended_17 = "#ff5555"

base00 = "#282a36"
base01 = "#44475a"
base02 = "#44475a"
base03 = "#6272a4"
base04 = "#bfbfbf"
base05 = "#f8f8f2"
base06 = "#ffffff"
base07 = "#ffffff"
base08 = "#ff5555"
base09 = "#ffb86c"
base0A = "#f1fa8c"
base0B = "#50fa7b"
base0C = "#8be9fd"
base0D = "#bd93f9"
base0E = "#ff79c6"
base0F = "#bd93f9"
