[data.colors]
name = "gruvbox_dark"
foreground = "#ebdbb2"
background = "#1d2021"

black = "#282828"
bright_black = "#928374"
red = "#cc241d"
bright_red = "#fb4934"
green = "#98971a"
bright_green = "#b8bb26"
yellow = "#d79921"
bright_yellow = "#fabd2f"
blue = "#458588"
bright_blue = "#83a598"
magenta = "#b16286"
bright_magenta = "#d3869b"
cyan = "#689d6a"
bright_cyan = "#8ec07c"
white = "#a89984"
bright_white = "#ebdbb2"

extended_16 = "#d65d0e"
extended_17 = "#fe8019"

base00 = "#1d2021"
base01 = "#282828"
base02 = "#3c3836"
base03 = "#504945"
base04 = "#665c54"
base05 = "#ebdbb2"
base06 = "#fbf1c7"
base07 = "#d5c4a1"
base08 = "#cc241d"
base09 = "#d65d0e"
base0A = "#d79921"
base0B = "#98971a"
base0C = "#689d6a"
base0D = "#458588"
base0E = "#b16286"
base0F = "#d65d0e"
