[data.colors]
name = "mocha"
foreground = "#cdd6f4"
background = "#1e1e2e"
black = "#45475a"
bright_black = "#585b70"
red = "#f38ba8"
bright_red = "#f38ba8"
green = "#a6e3a1"
bright_green = "#a6e3a1"
yellow = "#f9e2af"
bright_yellow = "#f9e2af"
blue = "#89b4fa"
bright_blue = "#89b4fa"
magenta = "#f5c2e7"
bright_magenta = "#f5c2e7"
cyan = "#94e2d5"
bright_cyan = "#94e2d5"
white = "#bac2de"
bright_white = "#a6adc8"
extended_16 = "#f5c2e7"
extended_17 = "#f38ba8"
