[data.colors]
name = "tokyonight-storm"
foreground = "#c0caf5"
background = "#24283b"

black = "#1d202f"
bright_black = "#414868"
red = "#f7768e"
bright_red = "#f7768e"
green = "#9ece6a"
bright_green = "#9ece6a"
yellow = "#e0af68"
bright_yellow = "#e0af68"
blue = "#7aa2f7"
bright_blue = "#7aa2f7"
magenta = "#bb9af7"
bright_magenta = "#bb9af7"
cyan = "#7dcfff"
bright_cyan = "#7dcfff"
white = "#a9b1d6"
bright_white = "#c0caf5"

extended_16 = "#ff9e64"
extended_17 = "#db4b4b"

base00 = "#24283b"
base01 = "#1f2335"
base02 = "#292e42"
base03 = "#3b4261"
base04 = "#565f89"
base05 = "#a9b1d6"
base06 = "#c0caf5"
base07 = "#d5d6db"
base08 = "#f7768e"
base09 = "#ff9e64"
base0A = "#e0af68"
base0B = "#9ece6a"
base0C = "#7dcfff"
base0D = "#7aa2f7"
base0E = "#bb9af7"
base0F = "#c0caf5"
