[data.colors]
name = "tokyonight"
foreground = "#c0caf5"
background = "#1a1b26"
black = "#282A36"
bright_black = "#414868"
red = "#f7768e"
bright_red = "#ff899d"
green = "#9ece6a"
bright_green = "#9fe044"
yellow = "#e0af68"
bright_yellow = "#faba4a"
blue = "#7aa2f7"
bright_blue = "#8db0ff"
magenta = "#bb9af7"
bright_magenta = "#c7a9ff"
cyan = "#7dcfff"
bright_cyan = "#a4daff"
white = "#a9b1d6"
bright_white = "#c0caf5"
extended_16 = "#ff9e64"
extended_17 = "#db4b4b"
