[data.colors]
name = "tokyonight-moon"
foreground = "#c8d3f5"
background = "#222436"

black = "#1b1d2b"
bright_black = "#444a73"
red = "#ff757f"
bright_red = "#ff757f"
green = "#c3e88d"
bright_green = "#c3e88d"
yellow = "#ffc777"
bright_yellow = "#ffc777"
blue = "#82aaff"
bright_blue = "#82aaff"
magenta = "#c099ff"
bright_magenta = "#c099ff"
cyan = "#86e1fc"
bright_cyan = "#86e1fc"
white = "#c8d3f5"
bright_white = "#d0d0d0"

extended_16 = "#ff966c"
extended_17 = "#c53b53"

base00 = "#222436"
base01 = "#1e2030"
base02 = "#2f334d"
base03 = "#444a73"
base04 = "#787c99"
base05 = "#c8d3f5"
base06 = "#eeeafe"
base07 = "#c099ff"
base08 = "#ff757f"
base09 = "#ff966c"
base0A = "#ffc777"
base0B = "#c3e88d"
base0C = "#86e1fc"
base0D = "#82aaff"
base0E = "#fca7ea"
base0F = "#c53b53"
