[data.colors]
name = "tokyonight"
foreground = "#c0caf5"
background = "#1a1b26"
black = "#282A36"
bright_black = "#414868"
red = "#f7768e"
bright_red = "#ff899d"
green = "#9ece6a"
bright_green = "#9fe044"
yellow = "#e0af68"
bright_yellow = "#faba4a"
blue = "#7aa2f7"
bright_blue = "#8db0ff"
magenta = "#bb9af7"
bright_magenta = "#c7a9ff"
cyan = "#7dcfff"
bright_cyan = "#a4daff"
white = "#a9b1d6"
bright_white = "#c0caf5"
extended_16 = "#ff9e64"
extended_17 = "#db4b4b"

base00 = "#24283b"
base01 = "#1f2335"
base02 = "#292e42"
base03 = "#565f89"
base04 = "#a9b1d6"
base05 = "#c0caf5"
base06 = "#c0caf5"
base07 = "#c0caf5"
base08 = "#f7768e"
base09 = "#ff9e64"
base0A = "#e0af68"
base0B = "#9ece6a"
base0C = "#1abc9c"
base0D = "#41a6b5"
base0E = "#bb9af7"
base0F = "#ff007c"
