[packages]
common = [
  "bash-completion",
  "bat",
  "bitwarden",
  "chezmoi",
  "docker",
  "docker-compose",
  "direvn",
  "eza",
  "fd",
  "firefox",
  "fzf",
  "git",
  "imagemagick",
  "inotify-tools",
  "jq",
  "kitty",
  "lazygit",
  "less",
  "man-db",
  "openssh",
  "python",
  "python-pip",
  "python-virtualenv",
  "ripgrep",
  "rofi",
  "starship",
  "tailscale",
  "tmux",
  "ttf-jetbrains-mono-nerd",
  "unzip",
  "wget",
  "wl-clipboard",
  "yazi",
  "zoxide",
  "zsh",
]
  work = ["dbeaver"]
  neovim = ["neovim", "wl-clipboard", "python-pynvim", "npm", "luarocks"]
[aur]
  common = ["sesh", "chezmoi_modify_manager", "google-chrome"]
  work = ["zoom", "postman-bin", "phpstorm"]
[hyprland]
  common = [
    "cliphist",
    "hyprland",
    "hypridle",
    "hyprlock",
    "hyprpaper",
    "hyprcursor",
    "hyprgraphics",
    "hyprland-protocols",
    "hyprland-qt-support",
    "hyprland-qtutils",
    "hyprlang",
    "hyprpolkitagent",
    "xdg-desktop-portal-hyprland",
    "thunar",
    "uwsm",
    "udisks2",
    "udiskie",
    "xdg-desktop-portal-hyprland",
    "qt5-wayland",
    "qt6-wayland",
    "waybar",
    "swaync",
    "cantarell-fonts",
  ]
  aur = ["pyprland", "wlogout"]

[scripts]
functions = '''
pac_install() {
  echo "Installing $1 ..."
  sudo pacman -S --noconfirm --needed "$1" >/dev/null 2>&1
}

yay_install() {
  echo "Yay Installing $1 ..."
  yay -S --noconfirm --needed "$1" >/dev/null 2>&1
}
'''
