[packages]
common = [
  "bash-completion",
  "bat",
  "bitwarden",
  "bitwarden-cli",
  "btop",
  "chezmoi",
  "direnv",
  "docker",
  "docker-compose",
  "eza",
  "fd",
  "firefox",
  "fzf",
  "git",
  "imagemagick",
  "inotify-tools",
  "jq",
  "kitty",
  "lazygit",
  "less",
  "luarocks",
  "man-db",
  "meld",
  "neovim",
  "npm",
  "openssh",
  "python",
  "python-pip",
  "python-pynvim",
  "python-virtualenv",
  "remmina",
  "ripgrep",
  "rofi",
  "starship",
  "tailscale",
  "tmux",
  "ttf-jetbrains-mono-nerd",
  "unzip",
  "wget",
  "wl-clipboard",
  "yakuake",
  "yazi",
  "zoxide",
  "zsh",
]
  work = ["dbeaver"]
[aur]
  common = [
  "backintime",
  "chezmoi_modify_manager",
  "google-chrome",
  "ktailctl",
  "kwin-scripts-krohnkite",
  "sesh",
  "todoist-wrapper-bin",
]
  work = ["iacs", "zoom", "postman-bin", "phpstorm"]
[hyprland]
  common = [
    "cliphist",
    "hyprland",
    "hypridle",
    "hyprlock",
    "hyprpaper",
    "hyprcursor",
    "hyprgraphics",
    "hyprland-protocols",
    "hyprland-qt-support",
    "hyprland-qtutils",
    "hyprlang",
    "hyprpolkitagent",
    "xdg-desktop-portal-hyprland",
    "thunar",
    "uwsm",
    "udisks2",
    "udiskie",
    "xdg-desktop-portal-hyprland",
    "qt5-wayland",
    "qt6-wayland",
    "waybar",
    "swaync",
    "cantarell-fonts",
  ]
  aur = ["pyprland", "wlogout"]
