[scripts]
functions = '''
pac_install() {
  echo "Installing $1 ..."
  sudo pacman -S --noconfirm --needed "$1" >/dev/null 2>&1
}

yay_install() {
  echo "Yay Installing $1 ..."
  yay -S --noconfirm --needed "$1" >/dev/null 2>&1
}

dnf_install() {
  echo "Installing DNF Package $1 ..."
  sudo dnf install --assumeyes "$1" >/dev/null 2>&1
}
'''

