[colors.tokyonight]
foreground = "#c0caf5" # foreground
background = "#1a1b26" # background

# Black
black = "#282A36"
bright_black = "#414868"

# Red
red = "#f7768e"        # red
bright_red = "#ff899d"

# Green
green = "#9ece6a"        # green
bright_green = "#9fe044"

# Yellow
yellow = "#e0af68"        # yellow
bright_yellow = "#faba4a"

# Blue
blue = "#7aa2f7"        # blue
bright_blue = "#8db0ff"

# Magenta
magenta = "#bb9af7"        # pink
bright_magenta = "#c7a9ff"

# Cyan
cyan = "#7dcfff"        # cyan
bright_cyan = "#a4daff"

# White
white = "#a9b1d6"
bright_white = "#c0caf5"

# Extended
extended_16 = "#ff9e64"
extended_17 = "#db4b4b"
